### ISSUE TITLE
Error after update to macOS 12.3

### ISSUE THREAD

**Issue by geimist** [timdoug/unpkg#7]
Error message: 
_**Missing interpreter**
The interpreter '/usr/bin/python' could not be found._

Obviously unpkg awaits the removed Python interpreter. Would Python3 be an option because it is installed by default?

**Comment by tjluoma** [comment]
The script does not work in python3. The `print` function needs to be used, but I don't know enough `python` to fix it.

And there may be many other issues. I assume if porting to `python3` was easy it would have been done long ago. I hope it's possible without too much of a re-write.

**Comment by timdoug** [comment]
Thanks both for the reports! I've released a new v4.8 ported to Python3 that works on 12.3 -- let me know if you have any issues.
